name: Deploy to Amazon ECS

on:
  create:

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: cicd-poc           # set this to your Amazon ECR repository name
  ECS_SERVICE: cicd_poc_service                 # set this to your Amazon ECS service name
  ECS_CLUSTER: cicd_poc # set this to your                 # set this to your Amazon ECS cluster name
  CONTAINER_NAME: cicd_poc           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: $GITHUB_REF_NAME

    steps:
      - name: See if env creates
        run: echo $GITHUB_REF_NAME got made
        shell: bash
