name: Deploy to Amazon ECS

on:
  delete:
    braches-ignore:
      - main
      - stg
      - dev

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1

jobs:
  build-branch-infra:
    name: Delete Branch Infrastructure
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
          
      - name: Terraform Init
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          ENV_NAME: ${{ github.ref_name }}
        run: |
          cd application
          terraform init
      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          ENV_NAME: ${{ github.ref_name }}
        run: |
          cd application
          terraform workspace new $ENV_NAME || terraform workspace select $ENV_NAME
          terraform destroy -auto-approve -var env_name=$ENV_NAME
          terraform workspace delete $ENV_NAME
      - name: Get GitHub App token
        uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c
        id: get-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Delete deployment environment
        uses: strumwolf/delete-deployment-environment@v2.2.3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          ENV_NAME: ${{ github.ref_name }}
        with:
          # Use a JWT created with your GitHub App's private key
          token: ${{ steps.get-token.outputs.token }}
          ref: ${{ github.ref_name }}
